//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veterinary.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointments
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Appointments()
        {
            this.MedicalRecords = new HashSet<MedicalRecords>();
            this.Transactions = new HashSet<Transactions>();
        }
    
        public int AppointmentId { get; set; }
        public int AnimalId { get; set; }
        public Nullable<int> DoctorId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> ReasonId { get; set; }
        public Nullable<int> StatusId { get; set; }
        public int ServiceId { get; set; }
    
        public virtual Animals Animals { get; set; }
        public virtual Personal Personal { get; set; }
        public virtual Reason Reason { get; set; }
        public virtual Services Services { get; set; }
        public virtual Status Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MedicalRecords> MedicalRecords { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transactions> Transactions { get; set; }
    }
}
